# ============================================================
# ai/evaluator.py — AI Evaluation Module (Phase-4)
# Analyzes student submission text using OpenAI GPT
# Falls back to heuristic scoring if API key is missing
# NEW: Content relevance validation against assignment context
# ============================================================

import json
import re
import os

# Try to import openai; graceful fallback if not installed
try:
    from openai import OpenAI
    OPENAI_AVAILABLE = True
except ImportError:
    OPENAI_AVAILABLE = False


# ── Prompt builders ──────────────────────────────────────────

def _build_prompt(text, max_marks=100, assignment_context=""):
    """Build the structured evaluation prompt with relevance check."""

    context_block = ""
    if assignment_context and assignment_context.strip():
        context_block = f"""
ASSIGNMENT CONTEXT (what the student was asked to do):
\"\"\"
{assignment_context[:3000]}
\"\"\"

"""

    return f"""You are an expert academic assignment evaluator.

{context_block}STUDENT SUBMISSION:
\"\"\"
{text[:4000]}
\"\"\"

Maximum possible marks: {max_marks}

{"STEP 1 — RELEVANCE CHECK:" if context_block else ""}
{"First, determine if this submission actually attempts to answer the assignment above." if context_block else ""}
{"Red flags for IRRELEVANT submissions:" if context_block else ""}
{"- The submission is just the question paper / assignment instructions copied or repeated back" if context_block else ""}
{"- The submission is unrelated notes, lecture content, or material from a different topic entirely" if context_block else ""}
{"- The submission does not attempt to answer ANY of the assignment questions or requirements" if context_block else ""}
{"- The submission is a blank document or contains only the student's name / roll number" if context_block else ""}
{"" if not context_block else ""}
{"STEP 2 — " if context_block else ""}Evaluate the submission on:
1. **Correctness** — Is the content factually accurate and technically correct?
2. **Clarity** — Is the writing clear, well-structured, and easy to understand?
3. **Completeness** — Does the answer cover all aspects of the topic thoroughly?

{"STEP 3 — " if context_block else ""}AI Detection: Estimate the probability that this text was generated by AI.

You MUST respond in this exact JSON format (no extra text, just JSON):
{{
  "is_relevant": <true or false — {"does the submission actually answer the assignment?" if context_block else "set to true if no assignment context is available"}>,
  "relevance_reason": "<one-line explanation of why relevant or irrelevant>",
  "score": <number between 0 and {max_marks}>,
  "feedback": "<2-3 lines of constructive feedback>",
  "ai_probability": <number between 0 and 100 indicating likelihood this was AI-generated>
}}

CRITICAL RULES:
- If is_relevant is FALSE, score MUST be 0 and feedback MUST explain why the submission was rejected.
- {"If no assignment context is provided, assume is_relevant is true and evaluate normally." if not context_block else "Compare the submission content against the assignment context carefully."}

Guidelines for scoring (only when relevant):
- 90-100%: Excellent — thorough, accurate, well-written
- 75-89%: Good — mostly correct with minor gaps
- 60-74%: Average — acceptable but needs improvement
- 40-59%: Below Average — significant gaps or errors
- 0-39%: Poor — major issues or largely incomplete

Guidelines for AI probability:
- Look for signs of AI-generated text: overly formal tone, generic phrasing, lack of personal insight, perfect grammar with no human touch
- 0-20%: Likely human-written
- 21-50%: Some AI characteristics
- 51-80%: Likely AI-assisted
- 81-100%: Almost certainly AI-generated"""


# ── Response parser ──────────────────────────────────────────

def _parse_ai_response(response_text, max_marks=100):
    """Parse the JSON response from GPT. Returns dict or None."""
    try:
        # Try direct JSON parse
        data = json.loads(response_text.strip())
    except json.JSONDecodeError:
        # Try to extract JSON from markdown code blocks
        match = re.search(r'\{[^{}]*"score"[^{}]*\}', response_text, re.DOTALL)
        if match:
            try:
                data = json.loads(match.group())
            except json.JSONDecodeError:
                return None
        else:
            return None

    # Validate and clamp values
    score = min(max(float(data.get("score", 0)), 0), max_marks)
    feedback = str(data.get("feedback", "No feedback generated."))
    ai_prob = min(max(float(data.get("ai_probability", 0)), 0), 100)
    is_relevant = data.get("is_relevant", True)
    relevance_reason = str(data.get("relevance_reason", ""))

    # Enforce: if not relevant, score must be 0
    if not is_relevant:
        score = 0

    return {
        "score": round(score, 1),
        "feedback": feedback,
        "ai_probability": round(ai_prob, 1),
        "is_relevant": bool(is_relevant),
        "relevance_reason": relevance_reason,
    }


# ── Heuristic relevance checker ─────────────────────────────

def _check_relevance_heuristic(submission_text, assignment_context):
    """
    Basic keyword-overlap relevance check when OpenAI is not available.
    Returns (is_relevant: bool, reason: str)
    """
    if not assignment_context or not assignment_context.strip():
        return True, "No assignment context available — assumed relevant."

    # Normalize texts
    sub_lower = submission_text.lower()
    ctx_lower = assignment_context.lower()

    # ── Check 1: Is the submission just the question paper copied? ──
    # Compare the two texts for high similarity
    sub_words = set(sub_lower.split())
    ctx_words = set(ctx_lower.split())

    if len(sub_words) > 10 and len(ctx_words) > 10:
        # Jaccard similarity between submission and assignment context
        intersection = sub_words & ctx_words
        union = sub_words | ctx_words
        jaccard = len(intersection) / len(union) if union else 0

        # If > 80% overlap, the student likely just uploaded the question paper
        if jaccard > 0.80:
            return False, "Submission is nearly identical to the assignment/question paper — likely a copy of the questions, not answers."

    # ── Check 2: Extract meaningful keywords from assignment ──
    # Remove common stopwords and short words
    stopwords = {
        'the', 'a', 'an', 'is', 'are', 'was', 'were', 'be', 'been', 'being',
        'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would', 'could',
        'should', 'may', 'might', 'shall', 'can', 'need', 'must', 'ought',
        'to', 'of', 'in', 'for', 'on', 'with', 'at', 'by', 'from', 'as',
        'into', 'through', 'during', 'before', 'after', 'above', 'below',
        'between', 'out', 'off', 'over', 'under', 'again', 'further', 'then',
        'once', 'and', 'but', 'or', 'nor', 'not', 'so', 'yet', 'both',
        'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'only',
        'own', 'same', 'than', 'too', 'very', 'just', 'because', 'if', 'while',
        'that', 'this', 'these', 'those', 'it', 'its', 'what', 'which', 'who',
        'whom', 'how', 'when', 'where', 'why', 'all', 'any', 'about', 'up',
        'your', 'you', 'we', 'they', 'he', 'she', 'me', 'my', 'his', 'her',
        'our', 'their', 'write', 'explain', 'describe', 'discuss', 'define',
        'answer', 'question', 'following', 'given', 'marks', 'assignment',
        'submission', 'student', 'maximum', 'total', 'note', 'notes',
    }

    ctx_keywords = {w for w in ctx_lower.split() if len(w) > 3 and w not in stopwords}
    sub_keywords = {w for w in sub_lower.split() if len(w) > 3 and w not in stopwords}

    if not ctx_keywords:
        return True, "Could not extract keywords from assignment — assumed relevant."

    # How many assignment keywords appear in the submission?
    overlap = ctx_keywords & sub_keywords
    overlap_ratio = len(overlap) / len(ctx_keywords) if ctx_keywords else 0

    # Very low overlap means submission is likely unrelated
    if overlap_ratio < 0.10 and len(ctx_keywords) >= 5:
        return False, f"Submission has very low topic overlap with the assignment ({overlap_ratio:.0%} keyword match). Likely unrelated content."

    # ── Check 3: Is the submission just a title/header with no substance? ──
    sub_word_count = len(submission_text.split())
    if sub_word_count < 15:
        return False, "Submission is too short to be a valid answer (fewer than 15 words)."

    return True, "Submission appears to address the assignment topic."


# ── Heuristic evaluator ─────────────────────────────────────

def _heuristic_evaluate(text, max_marks=100, assignment_context=""):
    """
    Fallback heuristic evaluator when OpenAI is unavailable.
    Now includes relevance checking against assignment context.
    """
    if not text or not text.strip():
        return {
            "score": 0,
            "feedback": "No content found in the submission. Please upload a valid document.",
            "ai_probability": 0,
            "is_relevant": False,
            "relevance_reason": "Submission is empty or contains no readable text.",
        }

    # ── Relevance check first ──
    is_relevant, relevance_reason = _check_relevance_heuristic(text, assignment_context)

    if not is_relevant:
        return {
            "score": 0,
            "feedback": f"Submission rejected: {relevance_reason}",
            "ai_probability": 0,
            "is_relevant": False,
            "relevance_reason": relevance_reason,
        }

    # ── Regular scoring (only if relevant) ──
    words = text.split()
    word_count = len(words)
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    sentence_count = len(sentences)
    paragraphs = [p.strip() for p in text.split('\n\n') if p.strip()]
    paragraph_count = len(paragraphs)

    # --- Score calculation ---
    score = 0

    # Length score (0-30 points on 100 scale)
    if word_count >= 500:
        length_score = 30
    elif word_count >= 200:
        length_score = 20
    elif word_count >= 50:
        length_score = 10
    else:
        length_score = 5
    score += length_score

    # Structure score (0-25 points)
    if paragraph_count >= 5:
        structure_score = 25
    elif paragraph_count >= 3:
        structure_score = 18
    elif paragraph_count >= 2:
        structure_score = 12
    else:
        structure_score = 5
    score += structure_score

    # Average sentence length (readability proxy) (0-20 points)
    if sentence_count > 0:
        avg_sentence_len = word_count / sentence_count
        if 10 <= avg_sentence_len <= 25:
            readability_score = 20
        elif 5 <= avg_sentence_len < 10 or 25 < avg_sentence_len <= 35:
            readability_score = 12
        else:
            readability_score = 5
    else:
        readability_score = 2
    score += readability_score

    # Vocabulary diversity (0-15 points)
    unique_words = len(set(w.lower() for w in words))
    if word_count > 0:
        diversity = unique_words / word_count
        if diversity >= 0.6:
            vocab_score = 15
        elif diversity >= 0.4:
            vocab_score = 10
        else:
            vocab_score = 5
    else:
        vocab_score = 0
    score += vocab_score

    # Keyword/technical content bonus (0-10 points)
    technical_patterns = [
        r'\b(therefore|however|furthermore|moreover|consequently)\b',
        r'\b(algorithm|function|variable|data|system|process|method)\b',
        r'\b(analysis|conclusion|result|hypothesis|experiment)\b',
        r'\b(figure|table|equation|formula|diagram)\b',
    ]
    tech_count = sum(1 for p in technical_patterns if re.search(p, text, re.IGNORECASE))
    tech_score = min(tech_count * 3, 10)
    score += tech_score

    # Scale to max_marks
    scaled_score = round((score / 100) * max_marks, 1)

    # --- Feedback ---
    feedback_parts = []
    if word_count < 50:
        feedback_parts.append("The submission is very short and lacks depth.")
    elif word_count < 200:
        feedback_parts.append("The submission could benefit from more detailed explanations.")
    else:
        feedback_parts.append("Good effort with reasonable content coverage.")

    if paragraph_count < 2:
        feedback_parts.append("Consider organizing your answer into multiple paragraphs for better readability.")
    else:
        feedback_parts.append("The answer has a decent structure.")

    if vocab_score < 10:
        feedback_parts.append("Try to use more varied vocabulary and technical terminology.")

    feedback = " ".join(feedback_parts)

    # --- AI probability (heuristic) ---
    ai_signals = 0
    # Very uniform sentence length suggests AI
    if sentence_count > 3:
        lengths = [len(s.split()) for s in sentences]
        avg_len = sum(lengths) / len(lengths)
        variance = sum((l - avg_len) ** 2 for l in lengths) / len(lengths)
        if variance < 5:
            ai_signals += 30
    # Perfect paragraph structure with headers
    if re.search(r'(Introduction|Conclusion|In conclusion|To summarize)', text, re.IGNORECASE):
        ai_signals += 15
    # Very high vocabulary diversity can indicate AI
    if word_count > 100 and diversity > 0.75:
        ai_signals += 15
    # Generic transitional phrases
    generic_count = len(re.findall(r'\b(in addition|on the other hand|it is important to note)\b', text, re.IGNORECASE))
    ai_signals += min(generic_count * 10, 25)

    ai_probability = min(ai_signals, 95)

    return {
        "score": scaled_score,
        "feedback": feedback,
        "ai_probability": round(ai_probability, 1),
        "is_relevant": True,
        "relevance_reason": relevance_reason,
    }


# ── Main entry point ────────────────────────────────────────

def evaluate_submission(text, max_marks=100, assignment_context=""):
    """
    Main evaluation function.

    Args:
        text (str): The extracted text from a student submission.
        max_marks (int): Maximum marks for the assignment (default 100).
        assignment_context (str): Combined assignment title + description + question paper text.

    Returns:
        dict: { "score", "feedback", "ai_probability", "is_relevant", "relevance_reason" }
    """
    if not text or not text.strip():
        return {
            "score": 0,
            "feedback": "No readable content found in the submission.",
            "ai_probability": 0,
            "is_relevant": False,
            "relevance_reason": "Submission is empty.",
        }

    # Try OpenAI first
    api_key = os.getenv("OPENAI_API_KEY", "").strip()
    if OPENAI_AVAILABLE and api_key:
        try:
            client = OpenAI(api_key=api_key)
            response = client.chat.completions.create(
                model="gpt-3.5-turbo",
                messages=[
                    {"role": "system", "content": "You are an expert academic evaluator. Respond only with valid JSON."},
                    {"role": "user", "content": _build_prompt(text, max_marks, assignment_context)},
                ],
                temperature=0.3,
                max_tokens=600,
            )
            ai_text = response.choices[0].message.content
            result = _parse_ai_response(ai_text, max_marks)
            if result:
                result["method"] = "openai"
                return result
        except Exception as e:
            print(f"[evaluator.py] OpenAI API call failed: {e}")
            # Fall through to heuristic

    # Fallback: heuristic evaluation
    result = _heuristic_evaluate(text, max_marks, assignment_context)
    result["method"] = "heuristic"
    return result
